version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - yum update -y
      - yum -y install unzip wget maven      
  build:
    commands:
      - mvn install
      - echo Build started on `date`
      - mvn test      
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/helloworld-1.1.jar
  discard-paths: yes
